WIP - #575 get resource changes after date API
quran/quran.com-api pull request #586
Opened 2022-08-29 04:04 UTC by adropofilm

**Objective**
1. Created `GET /changes?updated_after={date_time}` endpoint to get all resources updated after `date_time`.
2. Minor changes in README to reflect ruby version update + documentation details

**Questions**
1. Any tips on how I can get `resource_id` to be passed in as an optional query param, but still keeping the grabbing of `date_time` maintainable (date_time is filtered via scope)? Tried to see how yall were filtering params, etc now but got lost (still new to rails/ruby)
2. Where are  unit tests located? I tried to find them but couldn't, thought they'd be in /test but no such directory

2022-08-29 04:04 UTC, ahmedre commented
Deployed to: http://staging.quran.com:49180

2022-08-29 17:26 UTC, naveed-ahmad requested changes
JAK for your first PR! Some minor issues.

2022-08-29 17:26 UTC, naveed-ahmad commented on app/controllers/api/v4/resources_controller.rb
> +      @resources = ResourceContent.changes(updated_after)
How about following implementation? 

```
if time = after_timestamp
   @resources = ResourceContent.changes(after: time)
   render 
else 
  render_422("Invalid datetime format")
end 
```

```
def after_timestamp
  if time = params[:updated_after].presence
    time !~ /\D/ ? Time.at(time) : Time.parse(time)
  end
end
```

`updated_after` could be a date/time or unix time stamp.

2022-08-29 17:26 UTC, naveed-ahmad commented on app/controllers/application_controller.rb
> +  def valid_time?(datetime)
see above comment

2022-08-29 17:26 UTC, naveed-ahmad commented on app/models/resource_content.rb
> +  scope :changes, ->(updated_after) { where("updated_at > ?", updated_after) }
Class method makes more sense here.

2022-08-30 00:45 UTC, adropofilm commented on app/views/api/v4/resources/changes.json.streamer
> +                      :sub_type
fixed

2022-08-30 03:00 UTC, adropofilm commented on app/models/resource_content.rb
> +  scope :changes, ->(updated_after) { where("updated_at > ?", updated_after) }
fixed

2022-08-30 04:08 UTC, adropofilm commented on app/controllers/application_controller.rb
> +  def valid_time?(datetime)
Fixed

2022-08-30 04:13 UTC, adropofilm commented on app/controllers/api/v4/resources_controller.rb
> +      @resources = ResourceContent.changes(updated_after)
Fixed

2022-08-30 05:26 UTC, ahmedre commented
Deployed to: http://staging.quran.com:49181

2022-08-30 22:35 UTC, naveed-ahmad approved these changes

2022-08-30 22:35 UTC, merged