[QF-921]: introduces country_lanaguage_preference endpoint
quran/quran.com-api pull request #687
Opened 2024-09-23 13:14 UTC by mohsinayoob

closes #[QF-921](https://quranfoundation.atlassian.net/browse/QF-921)

2024-09-24 16:09 UTC, osamasayed requested changes

2024-09-24 16:09 UTC, osamasayed commented on app/controllers/api/qdc/resources_controller.rb
> +      end
Don't we need to also validate the language is valid e.g. someone enters `abc`

2024-09-24 16:09 UTC, osamasayed commented on app/controllers/api/qdc/resources_controller.rb
> +      if country.blank?
Don't we need to also validate the country is valid e.g. someone enters `abc`

2024-09-24 16:09 UTC, osamasayed commented on app/controllers/api/qdc/resources_controller.rb
> +      @default_mushaf = @preference.default_mushaf_id ? Mushaf.find(@preference.default_mushaf_id) : nil
We should filter by enabled Musahfs only

2024-09-24 16:09 UTC, osamasayed commented on app/controllers/api/qdc/resources_controller.rb
> +      @default_tafsir = @preference.default_tafsir_id ? ResourceContent.find(@preference.default_tafsir_id) : nil
We should filter tafsirs and translations by approved only

2024-09-25 06:58 UTC, mohsinayoob commented on db/migrate/20240918072240_create_country_language_preferences.rb
> +  end
In most cases we are using languages table in quran schema and also the other which are referring to language, they have relation with languages table of quran schema not i18n schema.
The issue here is we have to add unique constraint to iso_code filed of languages table to use it as foreign key. 
Making that change too

2024-09-28 02:28 UTC, osamasayed approved these changes

2024-10-01 19:06 UTC, merged